### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by AngelMonky** [TheWicklowWolf/BookBounty#10]
I am using docker on synology, I am getting a permission denied, and think this has to do with the PUID / PGID setup. I am not using the default 1000/1000, could you make this variable in the ENV variables so I can insert my own specific PUID / PGID? Currently the instance has to rights to write to the folder structure.

![image](https://github.com/user-attachments/assets/d4e5795b-c0ec-44db-b0c5-847ff48c11e3)

**Comment by rzilla75** [comment]
Have you tried manually entering those ENV variables? I believe that's what I needed to do on my QNAP. I also have a Synology and would be willing to do some testing on that box as well.

**Comment by AngelMonky** [comment]
Yes, tried a couple things, let me share the setup. tried to add net_admin as well in here.

![image](https://github.com/user-attachments/assets/35a5701f-014c-419d-8c99-0b0b6cc71784)
![image](https://github.com/user-attachments/assets/9d51c564-6a52-4665-a1b4-ea0e6a4fd9ee)
![image](https://github.com/user-attachments/assets/d3f0695b-2f96-412c-8fd7-2ab5bca60772)
![image](https://github.com/user-attachments/assets/aa75cf76-3fde-4366-bf5c-66b2d8b84348)
![image](https://github.com/user-attachments/assets/cec452ff-b7d7-4af0-b22d-eef4ec11f1e7)

**Comment by rzilla75** [comment]
For some reason my Synology is unable to locate bookbounty in the registry this morning. 

But your settings look similar to hat I have on my QNAP. 
I did make my "docker user" the owner of the config folder. In your case that would be "/docker/BookBounty"

**Comment by AngelMonky** [comment]
Do you mean the docker hub? You have to specifically search for your package: TheWicklowWolf/BookBounty then you can find it.

I tried this last week as well, and same result so should not be due to the registry I think ;(
Does seem like an amazing good app (BookBounty), It would even be better if this was done using readarr integration somehow. But I can imagine this would be a whole other thing to make :)

**Comment by TheWicklowWolf** [comment]
I am not familiar with the specific setup of Synology systems, but the process should be straightforward: you need to grant PUID/PGID (1000:1000) read and write access to both `/docker/BookBounty` and `/Media/Downloads/Complete` in your case.
