### ISSUE TITLE
Ability to search both fiction & non-fiction

### ISSUE THREAD

**Issue by garythebat** [TheWicklowWolf/BookBounty#14]
More of a request than an issue, is it possible to search fiction and non-fiction. So if the env variable is set to fiction, it tries fiction first and then non-fiction

**Comment by TheWicklowWolf** [comment]
Thanks for the suggestion. No plans for this since you can switch between the two in the settings modal, by setting the search type to either `fiction `or `non-fiction`.

**Comment by phoenix-limited** [comment]
For the folks trying to set up an automated/unattended set up without having two containers I would see this as useful. Is this a possibility?
