### ISSUE TITLE
Libgen 403 Error

### ISSUE THREAD

**Issue by alva-seal** [TheWicklowWolf/BookBounty#15]
Hello

I set up bookbonty, but i get a 403 Error in the logs, example below

`Libgen Connection Error: 403 Data: <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html> `

Did I set it up wrong or what could I do to change the error

**Comment by TheWicklowWolf** [comment]
Sounds like an issue on the LibGen side, or maybe you are using a VPN that is getting blocked by LibGen??

**Comment by alva-seal** [comment]
No im using it on my server without a vpn. But maybe they blocked a range of ips from that provider for some reason.

I will try to test it somewhere else.

Thanks for your answer

**Comment by TheWicklowWolf** [comment]
What happens if you access the same LibGen URL directly through a browser on your server? Does that work? 

Also, what type of machine are you using?

**Comment by alva-seal** [comment]
I use a headless Linux root server using Debian.
I have a calibre docker where i have a vnc and in this i used the browser and got a 403 too and a message:
```
Access from your host or network range is forbidden
We continually monitor our log files for excessive or undesirable requests. Abusers and bots might be banned.
```
So that’s defenetly a me problem sorry I bothered you, nothing you can change
