### ISSUE TITLE
Libgen Error

### ISSUE THREAD

**Issue by ryanpeplin** [TheWicklowWolf/BookBounty#18]
I keep getting Libgen error. Logs below.

```
**************************************************

BookBounty Version: 0.1.7

**************************************************
Loading Settings via config file
192.168.100.79 - - [2024-09-23 19:53:21] "GET / HTTP/1.1" 200 9614 0.008844
192.168.100.79 - - [2024-09-23 19:53:21] "GET /static/style.css HTTP/1.1" 304 177 0.001350
192.168.100.79 - - [2024-09-23 19:53:21] "GET /static/readarr.svg HTTP/1.1" 304 180 0.002535
192.168.100.79 - - [2024-09-23 19:53:21] "GET /static/libgen.png HTTP/1.1" 304 179 0.000661
192.168.100.79 - - [2024-09-23 19:53:21] "GET /static/script.js HTTP/1.1" 304 178 0.000802
192.168.100.79 - - [2024-09-23 19:53:21] "GET /socket.io/?EIO=4&transport=polling&t=P8XXCAn HTTP/1.1" 200 254 0.000447
192.168.100.79 - - [2024-09-23 19:53:21] "POST /socket.io/?EIO=4&transport=polling&t=P8XXCA_&sid=6jIHgqaUkQ1kBfH-AAAA HTTP/1.1" 200 200 0.001059
192.168.100.79 - - [2024-09-23 19:53:21] "GET /socket.io/?EIO=4&transport=polling&t=P8XXCB0&sid=6jIHgqaUkQ1kBfH-AAAA HTTP/1.1" 200 310 0.001860
192.168.100.79 - - [2024-09-23 19:53:21] "GET /socket.io/?EIO=4&transport=polling&t=P8XXCBB&sid=6jIHgqaUkQ1kBfH-AAAA HTTP/1.1" 200 157 0.046068
Accessing Readarr API
Searching for Book: Dan Brown - The Da Vinci Code
Libgen Connection Error: 404 Data: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8c7ecc1a7b04450d',t:'MTcyNzEzOTIwNC4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body></html>

Downloading Finished
Readarr library scan started
[2024-09-23 20:09:55 -0500] [1] [INFO] Handling signal: term
```

**Comment by TheWicklowWolf** [comment]
The error you're seeing is related to Libgen. The logs show a 404 Not Found error, meaning the requested URL on the Libgen server wasn’t available. This could be due to downtime or the resource being unavailable.

I don't think this is an issue with BookBounty since it can access the Readarr API and is requesting the right data from Libgen. The problem seems to be with Libgen not responding as expected. If you can't access or download from Libgen manually, BookBounty won’t be able to either.

**Comment by ryanpeplin** [comment]
Sorry I should have specified. I can access and use Libgen manually as normal. But book bounty can't access it. I've tried changing which Libgen multiple times, but none connect. But it also sounds like it might be a me issue.

**Comment by TheWicklowWolf** [comment]
Maybe your using a VPN or maybe that address is banned.. I’m aware there’s an option to change addresses, but `http://libgen.is` is the only one that should be functioning.

Note: The environmental variable `libgen_address` is intended for future use if additional sites are supported (though there are no immediate plans for this).

**Comment by ryanpeplin** [comment]
Ah. I did not realize that was just for future development. I had originally changed it because http://libgen.is was showing the error. I wasn't using a VPN but I will test using one.

Thank you for your help.

**Comment by TheWicklowWolf** [comment]
> I wasn't using a VPN but I will test using one.

I'm not saying you need to use a VPN. However, if you were using one, it could be helpful to turn it off and check if that resolves the issue. The same applies if you haven't been using one.

**Comment by ryanpeplin** [comment]
For what it's worth I finally got around to changing the `libgen_address` back to `http://libgen.is` and it started working again. Even without a VPN.
