### ISSUE TITLE
Option to Pull Only Wanted Books from Readarr

### ISSUE THREAD

**Issue by NovaCyntax** [TheWicklowWolf/BookBounty#2]
Currently, application pulls hundreds and hundreds of books if reading older authors. Monitoring only books marked as "wanted" in Readarr will speed up application usage by a lot. This could be done via an environment variable perhaps.

Current Behavior Example: If trying to get 2-3 books from Isaac Asimov (that are each marked as monitored in Readarr), the application will display hundreds and hundreds of books and essays from him, as he had around a thousand publications in his lifetime. This makes the user have to sift through many unwanted options. 

Suggested Behavior Example: Only the 2-3 books from Isaac Asimov (that are each marked as monitored in Readarr) will appear in the application. This keeps the user from having to sift through options.

Great work otherwise, I've long wondered why Readarr didn't have a native libgen capability built-in.

**Comment by TheWicklowWolf** [comment]
It currently pulls the wanted list from `/api/v1/wanted/missing` 
So whatever is on your Readarr Wanted page gets pulled in -> http://ip_address:8787/wanted/missing 

I suggest you unmonitor all books for that author and then only monitor the books you want. Then refresh BookBounty by hitting the Get Missing List

**Comment by NovaCyntax** [comment]
Apologies, my Readarr preference for adding a new book somehow was switched to monitoring all books from new authors. Not sure how that was reset. Fantastic program.

**Comment by TheWicklowWolf** [comment]
👍
