### ISSUE TITLE
How to use http_proxy

### ISSUE THREAD

**Issue by blender50** [TheWicklowWolf/BookBounty#20]
I'm new to BookBounty, and was wondering if there is a way to use it with privoxy. I tried to set http_proxy to the :8118 address of my VPN container running privoxy and it seemed to get a secure remote IP as expected, but once I did that the container seemed to try and use the VPN to connect to my Readarr which is on the LAN. 

Is there something I can do to get BookBounty to access Readarr locally and do its searches through the privoxy connection?

**Comment by TheWicklowWolf** [comment]
I'm sure there is, but I don't even know what `privoxy` is, so I can't help...

You can just clone the project and run it locally to get it to fit your use case, best of luck with it.

**Comment by blender50** [comment]
FYI privixy is a popular http proxy used by VPNs

<img width="860" alt="image" src="https://github.com/user-attachments/assets/25de5fac-be78-4af8-9ad4-a1145e774dee">

**Comment by blender50** [comment]
Thanks for getting back to me. I'm not trying to be snarky, or get you to change/develop BookBounty to fit my use case. FYI privoxy is a popular http proxy used by VPNs

<img width="860" alt="image" src="https://github.com/user-attachments/assets/25de5fac-be78-4af8-9ad4-a1145e774dee">

I was able to get things to work by excluding the readarr connection using the no_proxy env variable. 

Thanks for a really useful project.
