### ISSUE TITLE
[Request] - Add VPN Option

### ISSUE THREAD

**Issue by r2range** [TheWicklowWolf/BookBounty#21]
https://libgen.is/ is blocked here (Netherlands) and only accessibele by VPN.

Since the wiki only support 1 url at this moment.

libgen_address: The URL for Library Genesis. The only supported URL at present is http://libgen.is.

**Comment by TheWicklowWolf** [comment]
There are no plans to expand support for this feature, but you're welcome to fork the project to fit your needs. 

Contributions via pull requests are also welcome.
