### ISSUE TITLE
Feature Request: Move file to new dir after download complete

### ISSUE THREAD

**Issue by chiefcastor** [TheWicklowWolf/BookBounty#22]
I use Calibre and have it set up to auto import files when it sees them added to a certain directory. However, if I download the file to that directory Calibre fails to import because it notices the file before it is completed. Would it be possible to add an option to move the file to a new location after the download is completed?

**Comment by TheWicklowWolf** [comment]
This was specifically setup for use with Readarr so this is out of scope.
However I'm open to PRs.
