### ISSUE TITLE
Automatic Import / Readarr Scan doesnt work with calibre readarr setup

### ISSUE THREAD

**Issue by montana123** [TheWicklowWolf/BookBounty#24]
Hey,

so I have readarr setup with calibre. I have tried both methods file and folder but the readarr scan doesn't add the books.

So basically I had it setup to folder and bookbounty downloaded the folder and created a subfolder in author with the book in it. Scan from readarr doesn't find any new books.

With the file variant I tried with have a _unprocessed folder somewhere. 

bookbounty sends the readarr scan but readarr doesn't  import the books. It's still under missing. With a manual import in readarr the book gets imported.

Can you help me?

**Comment by TheWicklowWolf** [comment]
Have a look at: https://thewicklowwolf.github.io/
or specifically:
https://thewicklowwolf.github.io/eBook-stack-simplified/

This sounds like more of an issue for Readarr to be honest...
