### ISSUE TITLE
[req] Remove hardcoded UID & GID

### ISSUE THREAD

**Issue by kd00d** [TheWicklowWolf/BookBounty#26]
On a Synology nas, user and group id 1000:1000 does not exists and is difficult for the average user to create and causes permission issues.
Allowing PUID & GUID to be set as environmental variables would solve this.

Thank you.

**Comment by TheWicklowWolf** [comment]
I don't use Synology so this is not an issue for me. 

If someone what to submit a PR for this I will gladly review it.
