### ISSUE TITLE
Can't connect to Readarr? Fixed maybe?

### ISSUE THREAD

**Issue by BillDStrong** [TheWicklowWolf/BookBounty#4]
When trying to connect to Readarr, I get this error message:

> HTTPConnectionPool(host='192.168.1.50', port=8787): Max retries exceeded with url: /api/v1/wanted/missing?apikey=xxxxxxxxxxxxx&page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1460626d5e20>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

It has the correct api key, I have just hidden it here.

After adding an "/" to the end of the address, it is now working? Here is my working docker run, maybe I am an idiot? (Probably likely.)

> docker run
>   -d
>   --name='bookbounty'
>   --net='bridge'
>   -e TZ="America/New_York"
>   -e HOST_OS="Unraid"
>   -e HOST_HOSTNAME="Tower"
>   -e HOST_CONTAINERNAME="bookbounty"
>   -e 'readarr_address'='http://192.168.0.50:8787/'
>   -e 'readarr_api_key'='xxxxxxxxxx'
>   -e 'request_timeout'='120'
>   -e 'selected_language'='English'
>   -e 'preferred_extensions_fiction'='.epub, .mobi, .azw3, .djvu'
>   -e 'library_scan_on_completion'='True'
>   -e 'search_type'='fiction'
>   -e 'minimum_match_ratio'='90'
>   -e 'sync_schedule'=''
>   -e 'sleep_interval'='0'
>   -e 'libgen_address'='https://libgen.is'
>   -e 'selected_path_type'='file'
>   -e 'preferred_extensions_non_fiction'='.pdf, .epub, .mobi, .azw3, .djvu'
>   -l net.unraid.docker.managed=dockerman
>   -l net.unraid.docker.webui='http://[IP]:[PORT:5000]/'
>   -l net.unraid.docker.icon='https://raw.githubusercontent.com/JPDVM2014/icons/f140eab75e20d8d91766ab49cac3a7c59b443aa5/bookbounty.png'
>   -p '5000:5000/tcp'
>   -v '/mnt/cache/appdata/bookbounty':'/bookbounty/config':'rw'
>   -v '/mnt/defiant/media/bookbounty':'/bookbounty/downloads':'rw'
>   -v '/etc/localtime':'/etc/localtime':'ro'
>   --user 99:100 'thewicklowwolf/bookbounty:latest'
> b55f833a0288bd7cd3fa4f30e8740f505c06bd78df85d3f46ff5740412bd367d

**Comment by TheWicklowWolf** [comment]
> (host='192.168.**1**.50', port=8787
> -e 'readarr_address'='http://192.168.0.50:8787/'

Which of these is correct: `1.50` or `0.50`? 
Also you don't need the trailing `/`

Check the config file in `/mnt/cache/appdata/bookbounty`  and make sure it is as expected..
