### ISSUE TITLE
Request - Option to Set Port in Docker Config

### ISSUE THREAD

**Issue by mistersoup3** [TheWicklowWolf/BookBounty#5]
As the title says -- the default port overlaps with eBookBuddy, so I can only have one at a time with my current configuration (everything on the same network, behind a vpn container). 

If there is a way in the app configuration or as an environment variable to update the port, that would be very helpful.

**Comment by TheWicklowWolf** [comment]
In your `docker-compose.yml` you can simply specify a different port mapping, like this:

```yaml
    ports:
      - 6868:5000
```

**Comment by mistersoup3** [comment]
Example docker compose:

  bookbounty:
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: 'service:vpn'
    image: thewicklowwolf/bookbounty:latest
    container_name: bookbounty
    environment:
      - selected_path_type=folder
      - library_scan_on_completion=True
    volumes:
      - ${DFLT_CONFIG}/bookbounty/config:/bookbounty/config
      - ${DFLT_MEDIA_SRC}/books:/bookbounty/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

ebookbuddy:
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: 'service:vpn'
    image: thewicklowwolf/ebookbuddy:latest
    container_name: ebookbuddy
    volumes:
      - ${DFLT_CONFIG}/ebookbuddy/config:/ebookbuddy/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

**Comment by TheWicklowWolf** [comment]
Not too familiar with that setup. But I think your best bet is to give one of those containers a different IP address on that network, which should remove the port conflict.
Otherwise you can just fork the repo and adjust it to suit.

Best of luck with it
