### ISSUE TITLE
Multiple Libgen url

### ISSUE THREAD

**Issue by tbeaugelin** [TheWicklowWolf/BookBounty#7]
Hey!
Thanks for the awesome program, it’s quite powerful! I do however encounter a problem/would suggest an improvment.
Could it be possible to add support for multiple Libgen URL? In case the one registered is down, and or to multiple chances of a match to download.
I also encounter a problem in that I can download the books I want from my libgen URL just fine by using a web browser, but for some reason BB does not find them and return a No Link Found.

**Comment by TheWicklowWolf** [comment]
I did intend to do that and there is an environmental variable `libgen_address` that you can use to change the URL, but I don't think it will work as different sites require different parsing. And I've no plans to implement that at the minute.
