### ISSUE TITLE
LibriVox Audiobook Support

### ISSUE THREAD

**Issue by NovaCyntax** [TheWicklowWolf/BookBounty#8]
LibriVox (https://librivox.org/) is a collection of volunteer-produced recordings of books that are in the public domain. I've recently come across them and have listened to a number of books from their collection the past couple of months. You've produced a number of interesting and purpose-dedicated applications that I use frequently, and if you were looking for another project this site could serve as an audio alternative to libgen.

**Comment by TheWicklowWolf** [comment]
Thanks for your suggestion but it's not something that I will be getting involved with.
