### ISSUE TITLE
Unable to download non-fiction books. 

### ISSUE THREAD

**Issue by spyrosbazios** [TheWicklowWolf/BookBounty#9]
<img width="601" alt="Screenshot 2024-07-16 at 9 19 02 PM" src="https://github.com/user-attachments/assets/602bd69b-3a53-4066-bf23-e0576cb75f9d">

```    bookbounty  | Error accessing libgen API: HTTPSConnectionPool(host='libgen.is', port=443): Max retries exceeded with url: /search.php?req=How%20to%20Keep%20House%20While%20Drowning&column=title (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))) ```

Your help would be much appreciated!

**Comment by TheWicklowWolf** [comment]
Issue is most likely down to an issue on the `libgen.is` side.
